### ISSUE TITLE
Fix button color issue

### ISSUE THREAD

**Issue by LeeMaurin** [JasonFritsche/BreweryFinder#12]
The last button used stays highlighted in black.

**Comment by JasonFritsche** [comment]
This is happening on the Search Results page. When you click to view a website, the button stays highlighted until you click somewhere else on the page.

**Comment by jatinkumarg** [comment]
Hey, can I try?

**Comment by JasonFritsche** [comment]
Yeah sure thing. Just fork the repo, clone it, and have at it.

**Comment by jatinkumarg** [comment]
@JasonFritsche I have added a [PR](https://github.com/JasonFritsche/BreweryFinder/pull/14).

Can you please review it?

**Comment by JasonFritsche** [comment]
@jatinkumarg I am reopening this issue. Although the use of jQuery works, this issue can be resolved without using jQuery.

**Comment by JasonFritsche** [comment]
Fixed the issue by preventing the default behavior of the onMouseDown event.
