### ISSUE TITLE
project has both yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#18]
It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.

In the readme you already state to use npm, therefore the yarn files should be removed

**Comment by JasonFritsche** [comment]
Thanks. I'll handle this soon.

**Comment by JasonFritsche** [comment]
yarn.lock file removed. Thanks @cdrani

**Comment by cdrani** [comment]
No problem.
