### ISSUE TITLE
update text of unsuccessful search to be dependent on search type

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#22]
```html
  displayResult(brewery) {
    if (!brewery.length) {
      return (
        <h1 className="Kreon-Text text-center">
          We couldn't find anything in that location...
        </h1>
      );
    } else {
      return brewery.map(item => {
        return <Brewery key={item.id} item={item} />;
      });
    }
  }
```

This text is based on searches by either city or state. It will need to be updated, possibly to something like:
`Sorry, we couldn't find a brewery with the ${searchBy} of ${searchTerm}. Please try again with a different search filter perhaps.`

App should pass down searchBy and searchTerm props to BreweryList. 

__NOTE__: This should wait until #21 has been merged with the additional search options.

**Comment by JasonFritsche** [comment]
@cdrani This would be a great improvement. I added the 'enhacement', 'help wanted', and 'good first issue' labels. However, if you want to work on this just claim it here in the issue comments. Thanks.

**Comment by cdrani** [comment]
No problem. I'll take it up.

**Comment by cdrani** [comment]
Closing as it has already been merged.
