### ISSUE TITLE
search on enter key

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#24]
Enter key press while focused on search input should also submit form.

**Comment by JasonFritsche** [comment]
I added the 'enhancement', 'good first issue', and 'help wanted' labels. If no one claims this here in the near future I'll knock it out, or if you (@cdrani ) want to claim it, then go for it. Thanks.

**Comment by cdrani** [comment]
I'll take this up.

**Comment by JasonFritsche** [comment]
Thanks for handling this issue @cdrani
