### ISSUE TITLE
swatch or slate theme?

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#25]
## Swatch Theme

This project is currently using the Slate Bootswatch theme. https://bootswatch.com/slate/

Is Swatch a combo of Slate BootSwatch? Should it be changed to just Slate Theme?

**Comment by JasonFritsche** [comment]
Good catch, it's the Slate theme.

**Comment by JasonFritsche** [comment]
Updated the readme to reflect Slate Theme.
