### ISSUE TITLE
travisci setup for automatic builds and deployments

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#26]
Everything starting from React Stuff and down is not pertinent to this project - it's all about create-react-app. A simple ci/cd file could run build, tests, and deploy the app automatically which is especially good for pull requests reviews. 

I recommend [travisci](https://travis-ci.org/): https://medium.com/@sumn2u/automate-create-react-app-deployment-to-gh-pages-using-travis-ci-b2a97203680b.

/cc @JasonFritsche

**Comment by JasonFritsche** [comment]
@cdrani Would you mind chatting over Slack or Discord regarding setting up ci? I've used CircleCI in a past project, but have never set it up.

**Comment by cdrani** [comment]
Sure. I have slack. I have only set up travis before once, and then just copy and pasted it for most projects. We can try circleci, but the post above is pretty apt for this project.

**Comment by scottkenanderson** [comment]
I have set this up on my fork, see here for an example PR: https://github.com/scottkenanderson/BreweryFinder/pull/3/checks
