### ISSUE TITLE
Handle Empty search

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/BreweryFinder#34]
Currently if you click or press enter with no search parameter in the search input, you will get results. We should implement a check, if no search parameter is entered...don't let a search happen, else, let the search happen. This seems like a good first timer issue. Have fun!

**Comment by hjpatel16** [comment]
Hey, can I work on it?

**Comment by JasonFritsche** [comment]
Yes, that would be awesome.

**Comment by hjpatel16** [comment]
Can you look at my PR?

**Comment by JasonFritsche** [comment]
@hjpatel16 I merged your PR. This works fine. I'm going to open a new issue for the next step in this issue. I want a message that displays for like 3-4 seconds that will let the user know that "search can't be empty" or something similar.
