### ISSUE TITLE
Display message to the user if an empty search is performed

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/BreweryFinder#37]
Currently, if nothing is entered in the search input, and the user presses enter or clicks the button to search, a search is not performed. This behavior is fine. However, a message should be displayed that tells the user that the search bar cannot be empty.

 This can be a modal that pops up, or a paragraph or heading tag that is hidden, and then is displayed for maybe 3 or seconds. The message should say something like "Search cannot be empty" or "Please enter a search term", or something similar.

**Comment by cdrani** [comment]
Why is this necessary at all? Why not just disable the the search button if the input is empty. Additionally also cancelling the form submission if user presses enter key on an empty input.

**Comment by JasonFritsche** [comment]
This is just an elegant way of handling an empty search. It would be fine without it, but why not show a brief message. It doesn't have to be a modal, a paragraph tag that is shown for a brief period of time would be fine.

**Comment by PabloRosas17** [comment]
Does this issue still require help? I'd be glad to take it. Thanks !

**Comment by JasonFritsche** [comment]
Go for it. Thank you

**Comment by PabloRosas17** [comment]
I've implemented a preliminary on my branch, here is a giphy recording: [modal on empty search bar (https://media.giphy.com/media/MRFvELU6H2IojS7O4y/giphy.gif)

**Comment by PabloRosas17** [comment]
i'm not sure how the overall project will react, but i've added modal from bootstrap. meaning, i had to add bootstrap based on the documentation from [Modal API - React-Bootstrap](https://react-bootstrap.github.io/components/modal/), in specific, the documentation points towards

`import Modal from 'react-bootstrap/Modal'`

**Comment by cdrani** [comment]
@PabloRosas17: When you get the chance can you take a look at #42 code review?

**Comment by bonbon12** [comment]
Hi, what about using tool tips to display the "empty search" message.
I'm thinking of a few different ways:
->Either when they click on the search bar it displays

![image](https://user-images.githubusercontent.com/20958484/55495553-2b253b00-560b-11e9-854d-6366bcbcfd0e.png)

->Rendering it in after an empty search

Let me know what you guys think

**Comment by JasonFritsche** [comment]
@bonbon12 I don't think a tooltip is appropriate for this issue.
