### ISSUE TITLE
why the call to toLowerCase() when the string is manually typed in?

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#39]
https://github.com/JasonFritsche/BreweryFinder/blob/72b3f14a69480b54d7f430518a54f88d7405244e/src/App.js#L38

<details>
<summary>FIX ME</summary>
<p>

```js
!item.name.toLowerCase().includes('brewery in planning.') 
```

</p>
</details>

**Comment by JasonFritsche** [comment]
@cdrani Good eye. This is a good opportunity for a first time PR.

**Comment by niftytushar** [comment]
Created a PR for this #61
