### ISSUE TITLE
Update Style

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/BreweryFinder#4]
This project is currently using the Slate theme from Bootswatch. The CDN is linked in the index.html file. This doesn't necessarily need to be changed. Please feel free to submit any ideas that you have for updating the styling of the project.

**Comment by SahibArora** [comment]
I will give it a try.

**Comment by JasonFritsche** [comment]
@SahibArora If you want to do incremental changes that would be fine.

**Comment by JasonFritsche** [comment]
@SahibArora Thanks for your contribution to this project. I am leaving this issue open so that others can feel free to change the style. You are more than welcome to make more changes as you see fit as well.

**Comment by JasonFritsche** [comment]
I added #41.

**Comment by cdrani** [comment]
Closing as #70 merged in. Another issue will opened when/if a redesign is required.
