### ISSUE TITLE
setup some code linter like prettier or eslint to enforce code style

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#40]
I noticed the code differentiates between single and double quotes, semicolons and no semicolons, etc. I believe eslint is already included, but add a fix script so that code is fixed according to eslint's configs. 

Additionally, a pre-commit hook would be most effective, preventing commits until there are no eslint warnings or errors.

**Comment by cdrani** [comment]
ref #49

**Comment by JasonFritsche** [comment]
Thanks Charles. I accepted the PR.
