### ISSUE TITLE
hours of operation on cards

### ISSUE THREAD

**Issue by PabloRosas17** [JasonFritsche/BreweryFinder#45]
Having hours of operation on the displayed card results would be a handy benefit. This would be a feature for sure.

![Screen Shot 2019-03-24 at 3 54 12 PM](https://user-images.githubusercontent.com/5782902/54887198-61b1c780-4e4d-11e9-9471-448b5c8d448c.png)

**Comment by cdrani** [comment]
This is a good idea, but I think this should be added to #9, no? However what if we just extract the hours of operation for the current day and display that instead if they are open? 

// @JasonFritsche

**Comment by cdrani** [comment]
After a look at the api, I don't think we can add this type of information as it is not provided in the api. This would be too difficult and tedious work to get this data as some locations are bars, some microbreweries, etc. Furthermore, each website (if it has their schedule) is not uniformly formatted, making it almost impossible to scrape such data. Closing this issue. 

// @JasonFritsche @PabloRosas17
