### ISSUE TITLE
make footer stick to bottom

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#46]
![Screen Shot 2019-03-26 at 16 18 06](https://user-images.githubusercontent.com/18746599/55037312-f4d03600-4fe2-11e9-9c2d-3fd97c6916e4.png)
Make this stick to the bottom of the page.

**Comment by PabloRosas17** [comment]
my two cents, should we follow a sticky footer approach or a phantom div approach?
sticky would use react api built in functionality,
div would use more of a "hacky" way of doing this.

**Comment by cdrani** [comment]
I'm not quite sure what you mean by phantom div.

**Comment by PabloRosas17** [comment]
phantom div is a lose term used to represent the typical div approach for a footer in html.
in code, <footer id=footer><div id=footer-wrapper> ... [close], the phantom is the wrapper.

**Comment by cdrani** [comment]
Ok. Never heard that association before. Whichever is fine by me. Use your (or whoever takes this up) own discretion.

**Comment by abdiG** [comment]
Hey @cdrani, i managed to move the sticker to the bottom of the page. I also moved the sticker code to a new `Footer.js` file. The PR for this issue is #72 
![image](https://user-images.githubusercontent.com/46496734/56086670-e7f87280-5e29-11e9-982f-e45e817f3725.png)

**Comment by cdrani** [comment]
@abdiG: It looks like this was fixed and merged in the new redesign in #70. I am sorry that your efforts will have been for nought. However I really like that you separated out the Footer into its own component. Would you like to implement that again in a new issue? I could assign it to you.
