### ISSUE TITLE
refactor RadioButtonContainer components to be rendered from map

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#62]
Currently the four RadioButtonContainer's are just copied four times, with each one only having a single change - the searchBy parameter. This could be refactored using a map with an array of the searchBy paramters: ['city', 'state', 'name', 'type']

**Comment by PabloRosas17** [comment]
this one seems very "beginner friendly", can i please take this one on? thank you.

**Comment by cdrani** [comment]
Yup!

**Comment by PabloRosas17** [comment]
Is there any particular resource we can use or that is recommend for react ui features (such as this radio button container)?

**Comment by cdrani** [comment]
No. We can use any style guides and components we want. There's a lot available, such as bootstrap, bulma, material, semantic, etc, but it would be ideal if we could create all the styling on our own, considering this project is relatively small. Anyhow, this would need to be addressed in a different issue, and not this one.
