### ISSUE TITLE
Go for flat design

### ISSUE THREAD

**Issue by RocktimSaikia** [JasonFritsche/BreweryFinder#66]
As the project is still in its initial stage.I think its better to go for a more flat material inspired design than a page with a background image.Plus it's look more flashy right now.Like for the light background image you had to pop up the title text color with a flashy white color which does not look very good.So these are the few things on design, i suggest :
1) Flat material inspired  design
2) Make good use of shadows and gradient.
3) may be use small sized vector images for beer representation than a actual beer background image.
[Note : The image takes some time to load too ,may be not optimized properly.]

**Comment by cdrani** [comment]
@RocktimSaikia: Thanks for these insights. As this is mostly a learning project, all are encouraged to improve upon it with their ideas, especially in regards to design (ref #4). If you feel up to it, we would very much welcome a new re(design), whether it be a full overhaul or incremental updates. The third suggestion is very apt as the image is very heavy and could be optimized. I would suggest that you break these suggestions into individual issues and further elaborate on what each task entails. This way if you yourself cannot work on them, then any other willing contributor can take up the issue. Thanks.

**Comment by RocktimSaikia** [comment]
@cdrani actually i have some free time from my college for few weeks.I would very much like to work on these specified desings that i mentioned here if thats okey with you guys?!
