### ISSUE TITLE
Site Is Not Mobile Friendly

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/BreweryFinder#75]
Somewhere along the way, the site lost it's responsiveness.  The site needs to be mobile-friendly/responsive. I feel like this is a good first issue, but it's open to anyone. 
Thanks!

**Comment by chrisdesilva** [comment]
I can take this on tonight if no one's been assigned yet

**Comment by JasonFritsche** [comment]
@chrisdesilva it's all yours.
