### ISSUE TITLE
update style on BreweryList navbar

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#82]
The navbar at the top of BreweryList looks like this:
![Screen Shot 2019-04-20 at 13 10 42](https://user-images.githubusercontent.com/18746599/56461326-16b4a280-636e-11e9-97a5-58865b38aadb.png)

Things to fix:

* [ ] all that empty space should be removed
* [ ] make scrolling text larger
* [ ] center the scrolling text and the button horizontally and vertically (maybe try using flex or grid)
* [ ] align most right edge of button with right edge of most right edge brewery card

Any other changes you deem suitable will also be considered.

**Comment by prashkup** [comment]
Hello, @cdrani, it seems that the button and the text are now larger in the navbar than in the picture shown. Should they be larger? 

I am working on this issue.

**Comment by cdrani** [comment]
Yes. I think it might have been updated in a previous commit in the last week. I will update the task list. Thanks for taking up this issue.
