### ISSUE TITLE
unnecessary fetch on App.js first render

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#93]
## Current Behavior

When the page first renders, there's a network request to the brewery api even when a user has yet to enter a search term. This is unnecessary and could prove to be an issue if the api has a rate limit. Additionally, the api by default returns an array of objects regardless if parameters are provided.

## Expected Behavior

There should not be an api request on first load.

## Possible Solution

Prevent the api request altogether at first load. In the `useEffect` hook in **App.js** make this change:
```diff
- const searchChanged = searchTerm !== prevSearchTerm
+ const searchChanged = searchTerm && searchTerm !== prevSearchTerm
```

Please check the Network tab on page load to see that there's not a fetch request when the page first loads.

**Comment by NoobyScoob** [comment]
I changed it, it works fine now. But I think, making an API request using a handler instead making a network request every time the page renders (useEffect hook).
Also using "%20" in the search box also shows the output.
How can I submit PR?

**Comment by cdrani** [comment]
@NoobyScoob: Thanks for resolving this issue. 
> But I think, making an API request using a handler instead making a network request every time the page renders (useEffect hook) would be better.

I don't understand what you mean here. How is it better? Also the  `%20` bug will be fixed in the near future when I setup our own api that is more strict. The current api's default is to return an alphabetic list of breweries  in the US sorted by city. In the meantime if you want you can send in a fix for the `%20`, but it's not too serious.
