### ISSUE TITLE
use react-router-dom for conventional routing

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#94]
## Context

It's not a big deal, as the current routing implementation works, but to adhere to the convention, I would suggest using react-router-dom instead of the current diy routing configuration.

## Current Behavior

The useState hook is being used to keep track of which page to render. The state shouldn't need to be used to control page routing. Additionally, props and functions are being passed around to switch/reroute pages. 

## Expected Behavior

Remove all useState hooks and props relating to routing/pages and replace their functionality with react-router-dom. This will clean up the codebase and make it easier to test some of the related components.

**Comment by scottkenanderson** [comment]
I had a bash at this one too, I have a WIP PR that is only WIP as it would be better to merge my other two PRs first. It's also a little bit light on tests.
