### ISSUE TITLE
render Footer component in App component

### ISSUE THREAD

**Issue by cdrani** [JasonFritsche/BreweryFinder#96]
## Current Behavior

The Footer component should be displayed across all pages. Currently it is only rendered in the BrewerySearch component.

## Possible Solution

Move the Footer component out of the BrewerySearch component and into the App component.

**Comment by scottkenanderson** [comment]
I can pick this up.

**Comment by scottkenanderson** [comment]
https://github.com/JasonFritsche/BreweryFinder/pull/97

**Comment by scottkenanderson** [comment]
@cdrani
